[package]
name = "word_pdf_c"
version = "0.1.0"
edition = "2024"

[dependencies]
docx-rs = "0.4"
zip = "0.6"
quick-xml = { version = "0.23", features = ["serialize"] }
printpdf = "0.7"
image = "0.24"
log = "0.4"
env_logger = "0.9"
thiserror = "1.0"
uuid = { version = "1.16", features = ["v4"] }
